name: fastai
channels:
- pytorch-nightly
- fastai
- defaults
dependencies:
- fastcore>=1.3.8

#not working with new pytorch?
#- torchvision

- matplotlib
- pandas>=1.0.0
- requests
- pyyaml
- fastprogress>=0.2.4
- pillow>=6.0.0
- scikit-learn
- scipy
- spacy

- pytorch==1.13.0.dev20220522
- python<3.10.0

